spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
      auto-offset-reset: latest
    producer:
      bootstrap-servers:
        - localhost:29092,localhost:39092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:33066/commerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: john.doe
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
